### PR TITLE
skip check if directories are images/videos

### LINKED ISSUE #23: Dalia is throwing errors about skipped directories.
**Dalia Version**
Run `cargo run -- -V` to find the version.

**Describe the bug**
`dalia` tries to check if a directory is an image or a video and then throws an error. 

**To Reproduce**
1. Create a directory with name `buggy` and place there an image and a subdirectory.
2. Run `cargo run -- -p "./buggy"`

**Expected behavior**
Running `dalia` with provided path to pictures program should only scan for pictures and shouldn't care about directories.

**Logs**
If applicable, add the log output to help explain your problem.
```
$ cargo run -- -p "./buggy"
ERROR dalia::directory > Failed to determine if path: ./buggy/subdirectory is image or video. Error: Is a directory (os error 21)
```

### PR DESCRIPTION
**Pull request by simisimis**
When scanning provided path for images/videos now it will exclude directories from being checked.
Better way it would be to add another match arm checking if error is `IsADirectory` type, however this `io::ErrorKind` enum variant hasn't been stabilized yet: [issue](https://github.com/rust-lang/rust/issues/86442) therefore we need to check directories differently.
closes #23

### CODE REVIEW

File: src/mimetype.rs [hunk 1]
```diff
@@ -1,11 +1,15 @@
-use std::{io, path::Path};
+use std::{fs, io, path::Path};
 
 /// image_or_video determines whether a given path is an image or video file
 pub fn image_or_video<P: AsRef<Path>>(filename: &P) -> Result<bool, io::Error> {
```
Comment (gmarouli) [inline src/mimetype.rs:4]: Maybe we should change the name of the argument `filename` to `path` to denote that this path could be anything file or directory. What do you think?

**Review by gmarouli — APPROVED** [review]
LGTM! Thank you for fixing this!
